backbone: prajjwal1/bert-tiny
enable_ort: false
learning_rate: 0.01
loss_fn: null
metrics: !!python/object:torchmetrics.classification.f_beta.F1
  _LIGHTNING_GREATER_EQUAL_1_3: true
  _backward_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _buffers: !!python/object/apply:collections.OrderedDict
  - []
  _cache: null
  _computed: null
  _defaults:
    fn: !!python/object/apply:torch._utils._rebuild_tensor_v2
    - !!python/object/apply:torch.storage._load_from_bytes
      - !!binary |
        gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
        AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
        aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApMb25nU3RvcmFn
        ZQpxAVgOAAAAOTQxNjEwODkzNDEyOTZxAlgDAAAAY3B1cQNLAU50cQRRLoACXXEAWA4AAAA5NDE2
        MTA4OTM0MTI5NnEBYS4BAAAAAAAAAAAAAAAAAAAA
    - 0
    - !!python/tuple []
    - !!python/tuple []
    - false
    - !!python/object/apply:collections.OrderedDict
      - []
    fp: !!python/object/apply:torch._utils._rebuild_tensor_v2
    - !!python/object/apply:torch.storage._load_from_bytes
      - !!binary |
        gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
        AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
        aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApMb25nU3RvcmFn
        ZQpxAVgOAAAAOTQxNjEwODMxOTAyNzJxAlgDAAAAY3B1cQNLAU50cQRRLoACXXEAWA4AAAA5NDE2
        MTA4MzE5MDI3MnEBYS4BAAAAAAAAAAAAAAAAAAAA
    - 0
    - !!python/tuple []
    - !!python/tuple []
    - false
    - !!python/object/apply:collections.OrderedDict
      - []
    tn: !!python/object/apply:torch._utils._rebuild_tensor_v2
    - !!python/object/apply:torch.storage._load_from_bytes
      - !!binary |
        gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
        AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
        aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApMb25nU3RvcmFn
        ZQpxAVgOAAAAOTQxNjEwODkxNjk4NzJxAlgDAAAAY3B1cQNLAU50cQRRLoACXXEAWA4AAAA5NDE2
        MTA4OTE2OTg3MnEBYS4BAAAAAAAAAAAAAAAAAAAA
    - 0
    - !!python/tuple []
    - !!python/tuple []
    - false
    - !!python/object/apply:collections.OrderedDict
      - []
    tp: !!python/object/apply:torch._utils._rebuild_tensor_v2
    - !!python/object/apply:torch.storage._load_from_bytes
      - !!binary |
        gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
        AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
        aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApMb25nU3RvcmFn
        ZQpxAVgOAAAAOTQxNjEwODk5ODYwMTZxAlgDAAAAY3B1cQNLAU50cQRRLoACXXEAWA4AAAA5NDE2
        MTA4OTk4NjAxNnEBYS4BAAAAAAAAAAAAAAAAAAAA
    - 0
    - !!python/tuple []
    - !!python/tuple []
    - false
    - !!python/object/apply:collections.OrderedDict
      - []
  _forward_cache: null
  _forward_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _forward_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _is_full_backward_hook: null
  _is_synced: false
  _load_state_dict_post_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _load_state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _modules: !!python/object/apply:collections.OrderedDict
  - []
  _non_persistent_buffers_set: !!set {}
  _parameters: !!python/object/apply:collections.OrderedDict
  - []
  _persistent:
    fn: false
    fp: false
    tn: false
    tp: false
  _reductions:
    fn: &id001 !!python/name:torchmetrics.utilities.data.dim_zero_sum ''
    fp: *id001
    tn: *id001
    tp: *id001
  _should_unsync: true
  _state_dict_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _to_sync: true
  _update_called: false
  average: micro
  beta: 1.0
  compute_on_step: true
  dist_sync_fn: null
  dist_sync_on_step: false
  fn: !!python/object/apply:torch._utils._rebuild_tensor_v2
  - !!python/object/apply:torch.storage._load_from_bytes
    - !!binary |
      gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
      AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
      aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApMb25nU3RvcmFn
      ZQpxAVgOAAAAOTQxNjExMTE4MjY2NzJxAlgDAAAAY3B1cQNLAU50cQRRLoACXXEAWA4AAAA5NDE2
      MTExMTgyNjY3MnEBYS4BAAAAAAAAAAAAAAAAAAAA
  - 0
  - !!python/tuple []
  - !!python/tuple []
  - false
  - !!python/object/apply:collections.OrderedDict
    - []
  fp: !!python/object/apply:torch._utils._rebuild_tensor_v2
  - !!python/object/apply:torch.storage._load_from_bytes
    - !!binary |
      gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
      AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
      aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApMb25nU3RvcmFn
      ZQpxAVgOAAAAOTQxNjEwOTAxOTg0MTZxAlgDAAAAY3B1cQNLAU50cQRRLoACXXEAWA4AAAA5NDE2
      MTA5MDE5ODQxNnEBYS4BAAAAAAAAAAAAAAAAAAAA
  - 0
  - !!python/tuple []
  - !!python/tuple []
  - false
  - !!python/object/apply:collections.OrderedDict
    - []
  ignore_index: null
  mdmc_reduce: null
  multiclass: null
  num_classes: 2
  process_group: null
  reduce: micro
  threshold: 0.5
  tn: !!python/object/apply:torch._utils._rebuild_tensor_v2
  - !!python/object/apply:torch.storage._load_from_bytes
    - !!binary |
      gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
      AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
      aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApMb25nU3RvcmFn
      ZQpxAVgOAAAAOTQxNjEwMzgyNDU1MjBxAlgDAAAAY3B1cQNLAU50cQRRLoACXXEAWA4AAAA5NDE2
      MTAzODI0NTUyMHEBYS4BAAAAAAAAAAAAAAAAAAAA
  - 0
  - !!python/tuple []
  - !!python/tuple []
  - false
  - !!python/object/apply:collections.OrderedDict
    - []
  top_k: null
  tp: !!python/object/apply:torch._utils._rebuild_tensor_v2
  - !!python/object/apply:torch.storage._load_from_bytes
    - !!binary |
      gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
      AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
      aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApMb25nU3RvcmFn
      ZQpxAVgOAAAAOTQxNjEwNzAzMDM0NTZxAlgDAAAAY3B1cQNLAU50cQRRLoACXXEAWA4AAAA5NDE2
      MTA3MDMwMzQ1NnEBYS4BAAAAAAAAAAAAAAAAAAAA
  - 0
  - !!python/tuple []
  - !!python/tuple []
  - false
  - !!python/object/apply:collections.OrderedDict
    - []
  training: true
multi_label: false
num_classes: 2
optimizer: !!python/name:torch.optim.adam.Adam ''
optimizer_kwargs: null
scheduler: null
scheduler_kwargs: null
serializer: null
