name: dl-explain
channels:
  - conda-forge
dependencies:
  - python=3.8.10
  - pip
  - pip:
      - ipykernel==6.13.0
      - lightning-flash[all]==0.5.0
      - mlflow==1.27.0
      - transformers==4.9.2
      - boto3==1.19.7
      - pytorch-lightning==1.4.9
      - datasets==1.9.0
      - click==8.0.3
      - databricks-cli==0.16.2
      - shap==0.40.0
      - ipywidgets==7.7.0
      - matplotlib==3.5.1
      - transformers-interpret==0.6.0
      - captum==0.5.0
      - protobuf==3.20.*
      - numpy==1.23.5
